--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars_files:
    - ../../vars/control.yml
  tasks:
  - name: Create JIRA EC2 instance
    ec2:
      region: "{{ region }}"
      key_name: "{{ ec2_key }}"
      image: "{{ app_image }}"
      instance_type: "{{ instance_type }}"
      group_id: "{{ webapps_sg_id }}"
      vpc_subnet_id: "{{ private_subnet_id }}"
      assign_public_ip: yes
      private_ip: 10.0.1.34
      wait: yes
      instance_tags:
        Name: jira.{{ customer_name }}.{{ tld }}
    register: jira

  - name: Create CONFLUENCE EC2 instance
    ec2:
      region: "{{ region }}"
      key_name: "{{ ec2_key }}"
      image: "{{ app_image }}"
      instance_type: "{{ instance_type }}"
      group_id: "{{ webapps_sg_id }}"
      vpc_subnet_id: "{{ private_subnet_id }}"
      assign_public_ip: yes
      private_ip: 10.0.1.64
      wait: yes
      instance_tags:
        Name: conf.{{ customer_name }}.{{ tld }}
    register: conf

  - name: Create Bastion EC2 instance
    ec2:
      region: "{{ region }}"
      key_name: "{{ jump_ec2_key }}"
      image: "{{ jump_image }}"
      instance_type: t2.micro
      group_id: "{{ jump_sg_id }}"
      vpc_subnet_id: "{{ public_subnet_id }}"
      assign_public_ip: yes
      private_ip: 10.0.0.132
      instance_tags:
        Name: jump.{{ customer_name }}.{{ tld }}
      wait: yes
    register: bastion

  - name: Store bastion IP in jump_ip
    set_fact:
      jump_ip: "{{ item.public_ip }}"
    with_items: "{{ bastion.instances }}"

  - name: Store jira IP in jira_ip
    set_fact:
      jira_ip: "{{ item.public_ip }}"
    with_items: "{{ jira.instances }}"

  - name: Store conf IP in conf_ip
    set_fact:
      conf_ip: "{{ item.public_ip }}"
    with_items: "{{ conf.instances }}"

  - name: Add jumphost to group
    add_host:
      hostname: "{{ jump_ip }}"
      groupname: jumphost

  - name: Add conf to host group
    add_host:
      hostname: conf.{{ customer_name }}.{{ tld }}
      groupname: conf
      ansible_ssh_common_args: -o ProxyCommand="ssh ec2-user@{{ jump_ip }} nc %h %p -w 10"

  - name: Add jira to host group
    add_host:
      hostname: jira.{{ customer_name }}.{{ tld }}
      groupname: jira
      ansible_ssh_common_args: -o ProxyCommand="ssh ec2-user@{{ jump_ip }} nc %h %p -w 10"