--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars_files:
    - ../../vars/control.yml
  tasks:
  - name: Create JIRA EC2 instance
    ec2:
      region: "{{ region }}"
      key_name: "{{ ec2_key }}"
      image: "{{ app_image }}"
      instance_type: "{{ instance_type }}"
      group_id: "{{ webapps_sg_id }}"
      vpc_subnet_id: "{{ private_subnet_id }}"
      assign_public_ip: yes
      private_ip: 10.0.1.34
      volumes:
        - device_name: /dev/sda1
          name: jira.{{ customer_name }}.{{ tld }}
          volume_size: "{{ jira_ec2_size }}"
          volume_type: gp2
          encrypted: True
      wait: yes
      instance_tags:
        Name: jira.{{ customer_name }}.{{ tld }}
        Application Name: ALM - Atlassian
        Cisco Mail Alias: atlassian-adm@cisco.com
        Customer: "{{ customer_name }}"
        Data Classification: Cisco Confidential
        Enviroment: "{{ prod_status }}"
        Resource Owner: atlassian-adm
        Security Compliance: N/A
    register: jira

  - name: Create CONFLUENCE EC2 instance
    ec2:
      region: "{{ region }}"
      key_name: "{{ ec2_key }}"
      image: "{{ app_image }}"
      instance_type: "{{ instance_type }}"
      group_id: "{{ webapps_sg_id }}"
      vpc_subnet_id: "{{ private_subnet_id }}"
      assign_public_ip: yes
      private_ip: 10.0.1.64
      volumes:
        - device_name: /dev/sda1
          name: conf.{{ customer_name }}.{{ tld }}
          volume_size: "{{ confluence_ec2_size }}"
          volume_type: gp2
          encrypted: True
      wait: yes
      instance_tags:
        Name: conf.{{ customer_name }}.{{ tld }}
        Application Name: ALM - Atlassian
        Cisco Mail Alias: atlassian-adm@cisco.com
        Customer: "{{ customer_name }}"
        Data Classification: Cisco Confidential
        Enviroment: "{{ prod_status }}"
        Resource Owner: atlassian-adm
        Security Compliance: N/A
    register: conf

  - name: Create Bastion EC2 instance
    ec2:
      region: "{{ region }}"
      key_name: "{{ jump_ec2_key }}"
      image: "{{ jump_image }}"
      instance_type: t2.micro
      group_id: "{{ jump_sg_id }}"
      vpc_subnet_id: "{{ public_subnet_id }}"
      assign_public_ip: yes
      private_ip: 10.0.0.132
      volumes:
        - device_name: /dev/sda1
          name: jump.{{ customer_name }}.{{ tld }}
          volume_size: 10
          volume_type: gp2
          encrypted: True
      instance_tags:
        Name: jump.{{ customer_name }}.{{ tld }}
        Application Name: ALM - Atlassian
        Cisco Mail Alias: atlassian-adm@cisco.com
        Customer: "{{ customer_name }}"
        Data Classification: Cisco Confidential
        Enviroment: "{{ prod_status }}"
        Resource Owner: atlassian-adm
        Security Compliance: N/A
      wait: yes
    register: bastion

  - name: Create Jira Elastic IP
    ec2_eip:
      region: "{{ region }}"
      device_id: "{{ jira.instance_ids[0] }}"
    register: jira_ip

  - name: Create Confluence Elastic IP
    ec2_eip:
      region: "{{ region }}"
      device_id: "{{ conf.instance_ids[0] }}"
    register: conf_ip

  - name: Store bastion IP in jump_ip
    set_fact:
      jump_ip: "{{ item.public_ip }}"
    with_items: "{{ bastion.instances }}"

  - name: Store jira IP in jira_ip
    set_fact:
      jira_ip: "{{ jira_ip.public_ip }}"

  - name: Store conf IP in conf_ip
    set_fact:
      conf_ip: "{{ conf_ip.public_ip }}"

  - name: Add jumphost to group
    add_host:
      hostname: "{{ jump_ip }}"
      groupname: jumphost

  - name: Add conf to host group
    add_host:
      hostname: conf.{{ customer_name }}.{{ tld }}
      groupname: conf
      ansible_ssh_common_args: -o ProxyCommand="ssh ec2-user@{{ jump_ip }} nc %h %p -w 10"

  - name: Add jira to host group
    add_host:
      hostname: jira.{{ customer_name }}.{{ tld }}
      groupname: jira
      ansible_ssh_common_args: -o ProxyCommand="ssh ec2-user@{{ jump_ip }} nc %h %p -w 10"