--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars_files:
    - ../../vars/control.yml
  tasks:
  - name: Create NACL
    ec2_vpc_nacl:
      name: alm-{{ customer_name }}-nacl
      state: present
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      subnets:
        - "{{ public_subnet_id }}"
        - "{{ private_subnet_id }}"
        - "{{ db_subnet_1_id }}"
        - "{{ db_subnet_2_id }}"
      ingress: [
        # rule no, protocol, allow/deny, cidr, icmp_code, icmp_type, port from, port to
        [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null],
      ]
      egress: [
        [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null],
      ]