--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars_files:
    - ../../vars/control.yml
  tasks:
  - name: Create RDS instance
    rds_instance:
      id: jira-{{ customer_name }}-{{ tld }}
      state: present
      region: "{{ region }}"
      vpc_security_group_ids: "{{ database_sg_id }}"
      subnet_group: alm-{{ customer_name }}-subnetgroup
      engine: postgres
      engine_version: 9.6.11
      storage_encrypted: True
      db_instance_class: db.t2.medium
      db_name: jiratest01
      username: jiratest01
      password: jiratest01
      allocated_storage: 20
      publicly_accessible: no

#  - name: Create RDS instance
#    rds_instance:
#      id: conf-{{ customer_name }}-nva
#      state: present
#      region: "{{ region }}"
#      vpc_security_group_ids: "{{ database_sg_id }}"
#      subnet_group: alm-{{ customer_name }}-subnetgroup
#      engine: postgres
#      engine_version: 9.6.11
#      storage_encrypted: True
#      db_instance_class: db.t2.medium
#      db_name: conftest01
#      username: conftest01
#      password: conftest01
#      allocated_storage: 20
#      publicly_accessible: no