--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars:
    ami_image: ami-011b3ccf1bd6db744
    customer_name: test
    region: us-east-1
    ec2_key: LA-us-east-1
    ssh_config_path: /home/jacopete/.ssh/config
    identity_file: /home/jacopete/.ssh/LA-us-east-1.pem
    atlassian_user: atlasian
    atlassian_group: atlasian
  tasks:
  - name: Create RDS postgreSQL instance
    rds:
      command: create
      subnet: alm-{{ customer_name }}-rds-subnetgroup
      vpc_security_groups: "{{ database_sg_id }}"
      region: "{{ region }}"
      publicly_accessible: no
      instance_name: rds-{{ customer_name }}-nva
      db_engine: postgres
      engine_version: 9.6.11
      size: 10
      instance_type: db.t2.micro
      db_name: jiratest01
      username: jiratest01
      password: jiratest01
      tags:
        Environment: alm-test-rds-creation
        Application: Atlassian