--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars_files:
    - ../../vars/control.yml
  tasks:
  - name: Create RDS Subnet Group
    rds_subnet_group:
      region: "{{ region }}"
      state: present
      name: alm-{{ customer_name }}-rds-subnetgroup
      description: Subnet Group for {{ customer_name }} RDS instance
      subnets:
        - "{{ db_subnet_1_id }}"
        - "{{ db_subnet_2_id }}"