--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars_files:
    - ../../vars/control.yml
  tasks:
  - name: Create Route 53 A record
    route53:
      state: present
      overwrite: yes
      zone: "{{ r53_zone }}"
      record: "{{ customer_name }}-jira.{{ r53_zone }}"
      type: A
      value:
        - "{{ jira_ip }}"

  - name: Create Route 53 A record
    route53:
      state: present
      overwrite: yes
      zone: "{{ r53_zone }}"
      record: "{{ customer_name }}-confluence.{{ r53_zone }}"
      type: A
      value:
        - "{{ conf_ip }}"
