---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: "customer_name"
      prompt: "What ID are we using for the customer?"
      default: "poc3"
      private: no
    - name: "region"
      prompt: "What region are we deploying them in?"
      default: "us-east-1"
      private: no
    - name: "tld"
      prompt: "What top level domain are you using?"
      default: "nva"
      private: no
  tasks:
  - set_fact:
      customer_name: "{{ customer_name  }}"
  - set_fact:
      region: "{{ region }}"
  - set_fact:
      tld: "{{ tld }}"

- import_playbook: tasks/create-vpc.yml
- import_playbook: tasks/bastion-config.yml
- import_playbook: tasks/configure-atlassian-instance.yml
- import_playbook: tasks/install-jira-opt.yml
- import_playbook: tasks/install-conf-opt.yml
