--- # AWS EC2 VPC NET module example
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create a VPC
    ec2_vpc_net:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      name: TestVPC
      state: present
      cidr_block: 10.0.0.0/16
    register: my_vpc

  - name: Set VPC ID in var
    set_fact:
      vpc_id: "{{ my_vpc.vpc.id }}"

  - name: Create IGW
    ec2_vpc_igw:
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
    register: my_vpc_igw

  - name: Set IGW ID in var
    set_fact:
      igw_id: "{{ my_vpc_igw.gateway_id }}"

  - name: Create Public1 Subnet
    ec2_vpc_subnet:
      resource_tags:
        Name: LabSubnet1-Public
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      cidr: 10.0.1.0/24
      az: us-east-1a
    register: public1_subnet

  - name: Set Public Subnet ID in var
    set_fact:
      public1_subnet_id: "{{ public1_subnet.subnet.id }}"

  - name: Create Public2 Subnet
    ec2_vpc_subnet:
      resource_tags:
        Name: LabSubnet2-Public
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      cidr: 10.0.2.0/24
      az: us-east-1b
    register: public2_subnet

  - name: Set Public Subnet ID in var
    set_fact:
      public2_subnet_id: "{{ public2_subnet.subnet.id }}"

  - name: Create Private3 Subnet
    ec2_vpc_subnet:
      resource_tags:
        Name: LabSubnet3-Private
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      cidr: 10.0.3.0/24
      az: us-east-1a
    register: private3_subnet

  - name: Set Public Subnet ID in var
    set_fact:
      private3_subnet_id: "{{ private3_subnet.subnet.id }}"

  - name: Create Private4 Subnet
    ec2_vpc_subnet:
      resource_tags:
        Name: LabSubnet4-Private
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      cidr: 10.0.4.0/24
      az: us-east-1b
    register: private4_subnet

  - name: Set Public Subnet ID in var
    set_fact:
      private4_subnet_id: "{{ private4_subnet.subnet.id }}"

  - name: Create Public Route Table
    ec2_vpc_route_table:
      tags:
        Name: LabRT-Public
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      subnets:
        - "{{ public1_subnet_id }}"
        - "{{ public2_subnet_id }}"
      routes:
        - dest: "0.0.0.0/0"
          gateway_id: "{{ igw_id }}"

  - name: Create Private Route Table
    ec2_vpc_route_table:
      tags:
        Name: LabRT-Private
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      subnets:
        - "{{ private3_subnet_id }}"
        - "{{ private4_subnet_id }}"
      routes:
        - dest: "0.0.0.0/0"

  - name: Create NACL1
    ec2_vpc_nacl:
      name: LabNACL1
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      subnets:
        - "{{ public1_subnet_id }}"
        - "{{ private3_subnet_id }}"
      ingress: [
        # rule no, protocol, allow/deny, cidr, icmp_code, icmp_type, port from, port to
        [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22],
        [110, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80],
      ]
      egress: [
        [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null],
      ]

  - name: Create NACL2
    ec2_vpc_nacl:
      name: LabNACL2
      state: present
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      subnets:
        - "{{ public2_subnet_id }}"
        - "{{ private4_subnet_id }}"
      ingress: [
        [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22],
        [110, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80],
        [120, 'tcp', 'allow', '0.0.0.0/0', null, null, 3389, 3389],
      ]
      egress: [
        [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null],
      ]

  - name: Create EC2 Security Group
    ec2_group:
      name: "LabSG-EC2"
      description: "LabSG-EC2"
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      rules:
        - proto: "tcp"
          from_port: "22"
          to_port: "22"
          cidr_ip: 0.0.0.0/0
        - proto: "tcp"
          from_port: "80"
          to_port: "80"
          cidr_ip: 0.0.0.0/0

  - name: Create RDS Security Group
    ec2_group:
      name: "LabSG-RDS"
      description: "LabSG-RDS"
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      rules:
        - proto: "tcp"
          from_port: "3389"
          to_port: "3389"
          cidr_ip: 0.0.0.0/0
        - proto: "tcp"
          from_port: "22"
          to_port: "22"
          cidr_ip: 0.0.0.0/0
        - proto: "tcp"
          from_port: "80"
          to_port: "80"
          cidr_ip: 0.0.0.0/0