awsec2_userdata.yml
--- # EC2 module provision and EC2_AMI module creation
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Start EC2 Instance and Configure for /JIRA/
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: ami-b70554c8
      instance_type: t2.micro
      count: 1
      key_name: mylatest-key-pair-usnva
      group_id: sg-0ec68a7d75233ce75
      user_data: "{{lookup('file', '/etc/ansible/playbooks/jira-init-script.sh')}}"
      wait: yes
    register: ec2

  - name: Create AMI
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: "{{ ec2.instances[0].id }}"
      wait: no
      name: mynewami
      tags:
        Name: MyNewAMI
        Service: TestAMIService
    register: instance