--- # This is an outline of the tasks that our playbook needs to accomplish
- hosts: local, awsinstance
- sudo
- connection: local, ssh
- ssh-agent, ssh-add key
- gather_facts: yes
- include credentials file

- connect to a running instance id
  - create atlasian user
  - install apache (jira)
  - edit index.html
  - restart apache
  - test port 80 and the default page