--- # Install nmap and update /etc/hosts
- hosts: jumphost
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars_files:
    - ../vars/control.yml
  tasks:
  - name: Set vars from localhost
    set_fact:
      customer_name: "{{hostvars['localhost']['customer_name']}}"
  - name: Wait for SSH on jumphost
    wait_for_connection:
      timeout: 120
  - name: Install nmap
    yum:
      name: "{{ item }}"
    with_items:
    - nmap
    notify:
    - Update /etc/hosts
  handlers:
  - name: Update /etc/hosts
    template:
      src: /etc/ansible/playbooks/templates/hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644