--- # Install nmap and update /etc/hosts
- hosts: jumphost
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars_files:
    - ../vars/control.yml
  tasks:
  - name: Wait for SSH on jumphost
    wait_for_connection:
      timeout: 120
  - name: Install nmap
    yum:
      name: "{{ item }}"
    with_items:
    - nmap
    notify:
    - UpdateETCHosts
  handlers:
  - name: UpdateETCHosts
    blockinfile:
      path: /etc/hosts
      block: |
        10.0.1.34     jira.{{ customer_name }}.nva
        10.0.1.64     conf.{{ customer_name }}.nva
        10.0.2.13     pgpool.{{ customer_name }}.nva
        10.0.2.11     pgres1.{{ customer_name }}.nva
        10.0.2.12     pgres2.{{ customer_name }}.nva