--- # Create atlasian user on both app hosts
- hosts: jira,conf
  connection: ssh
  remote_user: ec2-user
  become: yes
  vars_files:
    - ../vars/control.yml
  tasks:
    - name: Create Atlasian group
      group:
        name: "{{ atlassian_group }}"
        state: present

    - name: Create Atlasian user
      user:
        name: "{{ atlassian_user }}"
        group: "{{ atlassian_group }}"
        shell: /bin/bash

    - name: Copy iptables settings to instance
      copy:
        src: ../files/iptables.dump
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: 0600

    - name: Configure iptables from file
      shell: iptables-restore < /etc/sysconfig/iptables

    - name: Add EPEL repository
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

    - name: Enable rhui-REGION-rhel-server-extras and rhui-REGION-rhel-server-optional
      ini_file:
        dest: /etc/yum.repos.d/redhat-rhui.repo
        section: "{{ item }}"
        option: enabled
        value: 1
      with_items:
        - rhui-REGION-rhel-server-extras
        - rhui-REGION-rhel-server-optional

    - name: Install HTTPD, yum-utils, certbot-apache
      yum:
        name: ['httpd', 'yum-utils', 'certbot-apache']

    - name: Set permission on httpd
      file:
        path: /etc/httpd
        state: directory
        owner: "{{ atlassian_user }}"
        group: "{{ atlassian_group }}"
        recurse: yes

    - name: Enable HTTPD
      service:
        name: httpd
        enabled: yes