--- # Create atlasian user on both app hosts
- hosts: pgres
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  vars_files:
    - ../vars/control.yml
  tasks:
    - name: Create Postgres group
      group:
        name: "{{ postgres_group }}"
        state: present

    - name: Create Postgres user
      user:
        name: "{{ postgres_user }}"
        group: "{{ postgres_group }}"
        shell: /bin/bash