--- # Install jira on an AW EC2 instance
- hosts: conf
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  vars:
    image: ami-011b3ccf1bd6db744
    customer_name: test
    region: us-east-1
    ec2_key: LA-us-east-1
    ssh_config_path: /home/jacopete/.ssh/config
    identity_file: /home/jacopete/.ssh/LA-us-east-1.pem
    atlassian_user: atlasian
    atlassian_group: atlasian
  tasks:
    - name: Install httpd
      yum:
        name: "{{ item }}"
      with_items:
        - httpd

    - name: Update JAVA_HOME
      lineinfile:
        path: /home/atlasian/.bash_profile
        insertbefore: 'export PATH'
        line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre/'

    - name: Create confluence install directory
      file:
        path: /data/atlassian/confluence
        owner: atlasian
        group: atlasian
        state: directory
        mode: 0700

    - name: Create confluence-home directory
      file:
        path: /data/atlassian/confluence-home
        owner: atlasian
        group: atlasian
        state: directory
        mode: 0700

    - name: download tar ball
      get_url:
        url: https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-6.14.3.tar.gz
        dest: /data/atlassian/confluence
        mode: 0777

    - name: untar it in jira FS
      unarchive:
        src: /data/atlassian/confluence/atlassian-confluence-6.14.3.tar.gz
        dest: /data/atlassian/confluence
        owner: atlasian
        group: atlasian
        remote_src: yes

    - name: Update init.properties with confluence-home
      lineinfile:
        path: /data/atlassian/confluence/atlassian-confluence-6.14.3/confluence/WEB-INF/classes/confluence-init.properties
        regexp: '^# confluence.home='
        line: 'confluence.home="/data/atlassian/confluence-home"'

    - name: Start HTTPD
      service:
        name: httpd
        state: started

    - name: Start Confluence
      command: su - atlasian -c "/data/atlassian/confluence/atlassian-confluence-6.14.3/bin/start-confluence.sh"
