--- # Install jira on an AW EC2 instance
- hosts: jira
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  vars:
    java_home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre/
  tasks:
    - name: Install httpd and java
      yum:
        name: "{{ item }}"
      with_items:
        - httpd
        - java

    - name: Update JAVA_HOME
      lineinfile:
        path: /home/atlasian/.bash_profile
        insertbefore: 'export PATH'
        line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre/'

    - name: Create jira FS
      file:
        path: /data/atlassian/jira
        owner: atlasian
        group: atlasian
        state: directory
        mode: 0700

    - name: Create jira-home FS
      file:
        path: /data/atlassian/jira-home
        owner: atlasian
        group: atlasian
        state: directory
        mode: 0700

    - name: download tar ball
      get_url:
        url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-7.13.1.tar.gz
        dest: /data/atlassian/jira
        mode: 0777

    - name: untar it in jira FS
      unarchive:
        src: /data/atlassian/jira/atlassian-jira-software-7.13.1.tar.gz
        dest: /data/atlassian/jira
        owner: atlasian
        group: atlasian
        remote_src: yes

    - name: update setenv.sh with JIRA_HOME
      lineinfile:
        path: /data/atlassian/jira/atlassian-jira-software-7.13.1-standalone/bin/setenv.sh
        regexp: '^#JIRA_HOME='
        line: 'JIRA_HOME="/data/atlassian/jira-home"'

    - name: Start HTTPD
      service:
        name: httpd
        state: started

    - name: Start JIRA
      command: su - atlasian -c "/data/atlassian/jira/atlassian-jira-software-7.13.1-standalone/bin/start-jira.sh"
