--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars_files:
    - ../vars/control.yml
  tasks:
  - name: Get RDS connection endpoint
    rds:
      command: facts
      region: "{{ region }}"
      instance_name: rds-{{ customer_name }}-nva
    register: rds

  - debug:
      msg: "{{ rds.instance.endpoint }}"

  - name: Store rds_endpoint
    set_fact:
      rds_endpoint: "{{ rds.instance.endpoint }}"

  - debug:
      msg: "{{ rds_endpoint }}"