--- # AWS ALM VPC Creation
- hosts: localhost
  connection: local
  remote_user: jacopete
  become: no
  gather_facts: no
  vars:
    ami_image: ami-011b3ccf1bd6db744
    customer_name: test
    region: us-east-1
    ec2_key: LA-us-east-1
    ssh_config_path: /home/jacopete/.ssh/config
    identity_file: /home/jacopete/.ssh/LA-us-east-1.pem
    atlassian_user: atlasian
    atlassian_group: atlasian
  tasks:
  - name: Store RDS connection endpoint
    rds:
      command: facts
      region: "{{ region }}"
      instance_name: rds-{{ customer_name }}-nva
    register: rds

  - name: Store rds instance id
    set_fact:
      rds_endpoint: "{{ rds.instance.endpoint }}"